define mc = Character("[mc_name]", color="#c8ffc8")
define vladimir = Character("[vladimir_name]", color="#c8ffc8")
define anya = Character("[anya_name]", color="#c8ffc8")
define andrey = Character("Андрей", color="#c8ffc8")
define platon = Character("[platon_name]", color="c8ffc8")
